# wip
# https://github.com/git-chglog/git-chglog
# https://github.com/nuuday/github-changelog-action
name: Make changelog
on:
  # push:
  #   branches: [main]
  # schedule:
  #   - cron: "0/5 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name:
        run: |
          today=$(date '+%Y%m%d')
          wget -O /usr/local/bin/git-chglog https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64
          chmod 755 /usr/local/bin/git-chglog
          git-chglog -v
          git pull --tags
          git checkout -b releasenote/${today}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${today} -m "v${today}"
          git-chglog -o CHANGELOG.md
          git add .
          git commit -m "Add changes" -a
          git push --tags
          git push origin main
