name: Checkout
on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: echo recently commit
        run: echo "recently commit $(git rev-parse HEAD) GITHUB_SHA $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
      - name: check commit
        run: |
          # mainの最新コミットSHA1とトリガー時のコミットSHA1が違っている場合（過去のデプロイを再実行した時など）はエラー終了させる
          if [ "$(git rev-parse HEAD)" != "$GITHUB_SHA" ]; then
            echo "workflow cancelled!"
            exit 1
          fi
      - name: Finish
        run: echo Finish!
