name: Checkout
on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: echo recently commit
        run: echo "recently commit $(git rev-parse --short HEAD) GITHUB_SHA $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
      - name: check commit
        run: |
          if [ "$(git rev-parse HEAD)" = "$GITHUB_SHA" ]; then
            echo "workflow cancelled!"
            exit 1
          fi
      - name: Finish
        run: echo Finish!
