name: Move new issues into In progress

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: スプリントタスク管理
          column: In progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
