name: Print Secret Safety
on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Echo DATABASE_URL safely
        shell: bash
        run: |
          echo "DATABASE_URL: $(echo "$DATABASE_URL" | cut -d'@' -f2)"
