name: Print Secret Safety
on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Mask full secret
        shell: bash
        run: echo "::add-mask::$DATABASE_URL"

      - name: Echo DATABASE_URL safely
        shell: bash
        run: |
          # ユーザ名とパスワード部分を **** で隠す
          SAFE_URL=$(printf '%s\n' "$DATABASE_URL" | sed -E 's#://[^/@]+@#://****:****@#')
          echo "DATABASE_URL = $SAFE_URL"
