name: Print Secret Safety
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Echo DATABASE_URL safely
        shell: bash
        run: |
          echo "DATABASE_URL(host part): $(echo "$DATABASE_URL" | cut -d'@' -f2)"
