name: dispatch test
on:
  workflow_dispatch:

jobs:
  dispatch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
